name: Demo IC/CD

on:
  push:
    branches:
      - master
      - dev
  
  pull_request:
    branches: [master, dev]

env:
  PROJECT: "Github Actions Demo"
  COURSE: FT9

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: A bash command
        run: echo Hello

  hello:
    runs-on: macos-latest
    needs: [demo]
    steps:
      - name: Hello
        run: echo Welcome to Github Actions

  dev-only:
    runs-on: ubuntu:latest
    if: ${{ env.GITHUB_REF_NAME }} == 'dev'
    steps:
      - name: Run on dev only
        run: echo This is from dev
