name: Demo IC/CD

on:
  push:
    branches:
      - master
      - dev
  
  pull_request:
    branches: [master, dev]

jobs:
  build:
    name: Lint, test, build
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup cache
        uses: actions/cache@v3 
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Testing
        run: npm test

      - name: Building
        run: npm run build --production
