name: Demo IC/CD

on:
  push:
    branches:
      - master
      - dev
  
  pull_request:
    branches: [master, dev]

env:
  PROJECT: "Github Actions Demo"
  COURSE: FT9

jobs:
  demo:
    strategy:
      matrix:
        node: [14, 16, 18]
    runs-on: ubuntu-latest
    steps:
      - name: A bash command
        run: echo Hello

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Print out node version
        run: node --version

  hello:
    runs-on: macos-latest
    needs: [demo]
    steps:
      - name: Hello
        run: echo Welcome to Github Actions

    services:
      postgresql:
        image: postgres:14.2
        ports:
          - "5433:5432"
        env:
          POSTGRES_USER: "demo"
          POSTGRES_DB: "demo_db"
          POSTGRES_PASSWORD: "password"

  dev-only:
    runs-on: ubuntu:latest
    steps:
      - name: Run on dev only
        run: echo This is from dev
        if: env.GITHUB_REF_NAME == 'dev'
